sf: 4
model:
  base_learning_rate: 1e-04
  target: ldm.models.diffusion.ddpm.MPerceiver
  params:
    # parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 512
    channels: 4
    cond_stage_trainable: False   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    # for training only
    ckpt_path: ckpt/v2-1_512-ema-pruned.ckpt
    unfrozen_diff: False
    random_size: False
    time_replace: 1000
    use_usm: True
    #P2 weighting, we do not use in final version
    p2_gamma: ~
    p2_k: ~
    # ignore_keys: []

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModelDualcondV2
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: False
        legacy: False
        semb_channels: 512

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        # for training only
        ckpt_path: ckpt/v2-1_512-ema-pruned.ckpt
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"

    structcond_stage_config:
      target: ldm.modules.diffusionmodules.openaimodel.IRAdapter
      params:
        image_size: 96
        in_channels: 4
        model_channels: 128
        out_channels: 512
        num_res_blocks: 2
        attention_resolutions: [ 4, 2, 1 ]
        dropout: 0
        channel_mult: [ 1, 2, 3, 4 ]
        conv_resample: True
        dims: 2
        use_checkpoint: False
        use_fp16: False
        num_heads: 4
        num_head_channels: -1
        num_heads_upsample: -1
        use_scale_shift_norm: False
        resblock_updown: False
        use_new_attention_order: False

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 20
    wrap: false
    train:
      target: basicsr.data.all_in_one_dataset.all_in_one_trainset
      params:
        fix_sample: 300000
        root_lq: ['path_lq']
        root_gt: ['path_gt']
        crop_size: 512
        io_backend:
          type: disk
        use_hflip: False
        use_rot: False
    validation:
      target: basicsr.data.all_in_one_dataset.all_in_one_trainset
      params:
        fix_sample: 10
        root_lq: ['path_lq']
        root_gt: ['path_gt']
        crop_size: 512
        io_backend:
          type: disk
        use_hflip: False
        use_rot: False

test_data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 6
    wrap: false
    test:
      target: basicsr.data.all_in_one_dataset.all_in_one_testset
      params:
        gt_path: /path/to/gt/
        lq_path: /path/to/lq/
        crop_size: 512
        io_backend:
          type: disk
        gt_size: 512
        use_hflip: False
        use_rot: False

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1000
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 10
        increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 800000
    # accumulate_grad_batches: 4

